### ISSUE TITLE
logstash.conf need change

### ISSUE THREAD

**Issue by mscss** [Azure/azure-diagnostics-tools#105]
Need to change the read.me to this config for NSG Logs.

azureblob
  {
      storage_account_name => "xxxxxx"
      storage_access_key => "xxxxxx"
      container => "insights-logs-networksecuritygroupflowevent"
      registry_create_policy => "start_over"
      codec => "json"
      file_head_bytes => 12
      file_tail_bytes => 2
      # Possible options: `do_not_break`, `with_head_tail`, `without_head_tail`
      break_json_down_policy  => 'with_head_tail'
      break_json_batch_count => 2
      interval => 5
  }
}

**Comment by clguimanMSFT** [comment]
@mscss Are you referring to the now unused properties (break_json..) or also to something else?

**Comment by brahmnes** [comment]
The two break_json parameters are now obsoleted. The behavior is, the header and tail, if they are non-empty, will always be added.
