### ISSUE TITLE
Logstash ouput plugin for data from Event Hubs

### ISSUE THREAD

**Issue by anjo-swe** [Azure/azure-diagnostics-tools#116]
Hi,

Any plans on adding an output plugin for Event Hubs?

We currently push data to AWS Kinesis Firehose from Logstash and would like do to the same thing with Azure Event Hubs

Thanks,
Andreas

**Comment by brahmnes** [comment]
No plans yet.
Just curious, why do you want to send data to eventhub? And from eventhub, where would the data go to? Can it go directly from logstash to where you want instead?

**Comment by anjo-swe** [comment]
Hi @brahmnes,

In the AWS scenario it's been convenient to push data to Kinesis Firehose so that it later on can flow into Redshift or S3.

Looking at similar approach now for Azure where data go first to Event Hubs then to e.g. SQL Data Warehouse.

Having an output plugin directly SQL Data Warehouse could be interesting as well but feels more flexible to send data to a Pub/Sub system first.

**Comment by brahmnes** [comment]
Hi @anjo-swe 

That makes sense. We do take contributions, so if you like, feel free to submit a PR.

**Comment by brahmnes** [comment]
Hi @anjo-swe,

logstash-input-azureeventhub is now deprecated in favor of Elastic's implementation:
https://github.com/logstash-plugins/logstash-input-azure_event_hubs

If you like, please propose feature suggestions
