### ISSUE TITLE
Logstash Blob Input - Bignum out of Float range

### ISSUE THREAD

**Issue by AshKapow** [Azure/azure-diagnostics-tools#117]
We're using the Blob input plugin to pull in some web server logs from Blobs and I'm seeing the following error in the Messages log (about 70 every minute)

> /usr/share/logstash/vendor/bundle/jruby/1.9/gems/azure-storage-0.12.3.preview/lib/azure/storage/core/filter/exponential_retry_filter.rb:58 warning: Bignum out of Float range

This is the input code that I'm using

input {
  azureblob {
    storage_account_name => "${BLOB1_NAME}"
    storage_access_key => "${BLOB1_KEY}"
    container => "iislogs"
    codec => "line"
    type => "iis_log"
  }
  azureblob {
    storage_account_name => "${BLOB2_NAME}"
    storage_access_key => "${BLOB2_KEY}"
    container => "iislogs"
    codec => "line"
    type => "iis_log"
  }
  azureblob {
    storage_account_name => "${BLOB3_NAME}"
    storage_access_key => "${BLOB3_KEY}"
    container => "iislogs"
    codec => "line"
    type => "iis_log"
  }
  azureblob {
    storage_account_name => "${BLOB4_NAME}"
    storage_access_key => "${BLOB4_KEY}"
    container => "iislogs"
    codec => "line"
    type => "iis_log"
  }
}

**Comment by brahmnes** [comment]
The error is thrown from azure storage sdk. Looking at their code, it's a line of code like this:
      increment_delta = (@max_retry_interval - @min_retry_interval).fdiv(2**(@retry_count - 1)) * (2**(retry_data[:count] - 1));

It's hard to tell why by code inspection. Perhaps you can modify it with a rescue statement and see if retry_data[:count] or @retry_count is getting too big?

**Comment by brahmnes** [comment]
Hi @AshKapow,

I am closing this issue assuming this is no longer an issue for you. Please reactivate if this is still a problem.
