### ISSUE TITLE
Accessing deviceId from Event Data

### ISSUE THREAD

**Issue by mmarab** [Azure/azure-diagnostics-tools#118]
I'm struggling to access the device id, is this possible? Normally I would access the device id from Event data properties, just wondering how this is done with the logstash-input-azureeventhub plugin? 

eventData.SystemProperties["iothub-connection-device-id"]

**Comment by brahmnes** [comment]
Hi @mmarab,

The logstash-input-azureeventhub plugin currently gets all the properties and use only the offset property. I imagine it's possible to have the plugin accept a collection of system property names in the config, and it adds these properties to each event.

If you want to submit a PR, please feel free to do so.

**Comment by brahmnes** [comment]
Hi,

Logstash-input-azureeventhub plugin is now deprecated in favor of Elastic's version of the plugin.
Please visit https://github.com/logstash-plugins/logstash-input-azure_event_hubs
