### ISSUE TITLE
Try make use of the per-request lease id to simplify the lock model

### ISSUE THREAD

**Issue by xiaomi7732** [Azure/azure-diagnostics-tools#119]
Reference: https://github.com/Azure/azure-storage-ruby/issues/16
There was a limitation that we can't access the file even when we hold the lease id. The issue is fixed by the SDK now. When it is possible, we shall look into pull the implementation in and simplify our lock model.

**Comment by EmFl** [comment]
I think I might be able to work on this tomorrow, did you start anything on your side ?

**Comment by xiaomi7732** [comment]
@EmFI,  thanks so much for this pre-communication👍. I don't see anyone working on this at this point. Please kindly submit the PR when you are ready.

**Comment by EmFl** [comment]
submitted PR #136

**Comment by EmFl** [comment]
Should this be closed now that PR has been merged ?

**Comment by xiaomi7732** [comment]
@EmFl Of course 👍
