### ISSUE TITLE
New Gem push for logstash-input-azurewadtable

### ISSUE THREAD

**Issue by chris-evans** [Azure/azure-diagnostics-tools#123]
I recently had a pull request accepted for azure-diagnostics-tools and was hopeful we could push the new changes to rubygems.org (https://rubygems.org/gems/logstash-input-azurewadtable/versions/0.9.2).  I don't have rights.  I just would like to know if I should wait for this to be pushed or just issue a duplicate gem to rubygems under a different name.

Thanks again for the great project!

**Comment by xiaomi7732** [comment]
@chris-evans,
 Please find the new gem here: https://rubygems.org/gems/logstash-input-azurewadtable/versions/0.9.13
Thanks!
