### ISSUE TITLE
Where are the tests for logstash-input-azurewadtable?

### ISSUE THREAD

**Issue by ralphwillgoss** [Azure/azure-diagnostics-tools#125]
I can't seem to find any tests for the logstash-input-azurewadtable, in the /spec/inputs directory?
Am I looking in the wrong place?

**Comment by brahmnes** [comment]
Hi @ralphwillgoss 

There are no test code in this repo. Most tests have been done manually. As the codebase gets larger, test code will be more important.

Do you have suggestions?

**Comment by ralphwillgoss** [comment]
I want to make some modifications so the plugin works with the storage emulator and just wanted to check to see if there was any tests.

I'll write some and submit a PR.

**Comment by ralphwillgoss** [comment]
@brahmnes 
I've done a first pass at some basic integration tests, can you review before I submit a PR?
https://github.com/ralphwillgoss/azure-diagnostics-tools/commit/34876d656f78654ca6f476177de6b98e4f57d191

**Comment by brahmnes** [comment]
@ralphwillgoss 
Your test implementation looks reasonable. Thank you for implementing this!
