### ISSUE TITLE
Logstash Eventhub input should close all connections on stop

### ISSUE THREAD

**Issue by andrewvc** [Azure/azure-diagnostics-tools#129]
This plugin probably leaks connections on pipeline reload.

Consider adding

```ruby
def stop
  # wait for runner threads to stop...
  @runner_threads.each(&:join)
  # free up any used resources
  #CODE TO SHUTDOWN EVENTHUB CONNECTION
end
```

**Comment by jakelandis** [comment]
`logstash-input-azureeventhub` has been superseded by `logstash-input-azure_event_hubs`

Note the options have changed and may be viewed [here](https://github.com/logstash-plugins/logstash-input-azure_event_hubs/blob/master/docs/index.asciidoc) until they are properly added to the standard documentation. 

To install the new plugin:
```
bin/logstash-plugin install logstash-input-azure_event_hubs
```

If issues are found with the new plugin please submit issues to : https://github.com/logstash-plugins/logstash-input-azure_event_hubs/issues

**Comment by brahmnes** [comment]
Thanks @jakelandis !
