### ISSUE TITLE
Delete shutdown signal block

### ISSUE THREAD

**Issue by andrewvc** [Azure/azure-diagnostics-tools#130]
This block won't ever run `https://github.com/Azure/azure-diagnostics-tools/blob/master/Logstash/logstash-input-azureeventhub/lib/logstash/inputs/azureeventhub.rb#L117`, that exception should never be triggered.

**Comment by jakelandis** [comment]
`logstash-input-azureeventhub` has been superseded by `logstash-input-azure_event_hubs`

Note the options have changed and may be viewed [here](https://github.com/logstash-plugins/logstash-input-azure_event_hubs/blob/master/docs/index.asciidoc) until they are properly added to the standard documentation. 

To install the new plugin:
```
bin/logstash-plugin install logstash-input-azure_event_hubs
```

If issues are found with the new plugin please submit issues to : https://github.com/logstash-plugins/logstash-input-azure_event_hubs/issues

**Comment by brahmnes** [comment]
Thanks @jakelandis !
