### ISSUE TITLE
Logstash plugins need documentation

### ISSUE THREAD

**Issue by andrewvc** [Azure/azure-diagnostics-tools#131]
Each plugin needs documentation. You can use https://raw.githubusercontent.com/logstash-plugins/logstash-input-jdbc/master/docs/index.asciidoc as a template. You'll need one per plugin. 

Logstash docs are written in [ASCIIDoc syntax](http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/). There should be one file per plugin located in `docs/index.asciidoc`

**Comment by jakelandis** [comment]
`logstash-input-azureeventhub` has been superseded by `logstash-input-azure_event_hubs`

Note the options have changed and may be viewed [here](https://github.com/logstash-plugins/logstash-input-azure_event_hubs/blob/master/docs/index.asciidoc) until they are properly added to the standard documentation. 

To install the new plugin:
```
bin/logstash-plugin install logstash-input-azure_event_hubs
```

If issues are found with the new plugin please submit issues to : https://github.com/logstash-plugins/logstash-input-azure_event_hubs/issues

**Comment by brahmnes** [comment]
Thanks @jakelandis !
