### ISSUE TITLE
Eventhub input should use azure blob storage for locking

### ISSUE THREAD

**Issue by andrewvc** [Azure/azure-diagnostics-tools#132]
Currently the Eventhub input can't auto-assign partitions based on consumer group. This means that starting up multiple Logstashes to consume from a consumer group is problematic because users must manually manage partitions. 

This can be done with Azure storage as seen in this [guide](https://github.com/Azure/azure-event-hubs-java/blob/dev/ConsumingEvents.md#ownership-failover-and-epochs)

**Comment by jakelandis** [comment]
`logstash-input-azureeventhub` has been superseded by `logstash-input-azure_event_hubs`

Note the options have changed and may be viewed [here](https://github.com/logstash-plugins/logstash-input-azure_event_hubs/blob/master/docs/index.asciidoc) until they are properly added to the standard documentation. 

To install the new plugin:
```
bin/logstash-plugin install logstash-input-azure_event_hubs
```

If issues are found with the new plugin please submit issues to : https://github.com/logstash-plugins/logstash-input-azure_event_hubs/issues

**Comment by brahmnes** [comment]
Thanks @jakelandis !
