### ISSUE TITLE
Add unit tests to various Logstash plugins

### ISSUE THREAD

**Issue by andrewvc** [Azure/azure-diagnostics-tools#133]
The various Logstash plugins are all missing unit tests.

Some good examples of Logstash unit tests are [here](https://github.com/logstash-plugins/logstash-input-http_poller/blob/master/spec/inputs/http_poller_spec.rb)

You can also find general rspec guidelines at [betterspecs](http://betterspecs.org/).

Tests should be runnable with `bundle exec rspec spec`.

The tests should also be runnable under Travis CI.

**Comment by jakelandis** [comment]
`logstash-input-azureeventhub` has been superseded by `logstash-input-azure_event_hubs`

Note the options have changed and may be viewed [here](https://github.com/logstash-plugins/logstash-input-azure_event_hubs/blob/master/docs/index.asciidoc) until they are properly added to the standard documentation. 

To install the new plugin:
```
bin/logstash-plugin install logstash-input-azure_event_hubs
```

If issues are found with the new plugin please submit issues to : https://github.com/logstash-plugins/logstash-input-azure_event_hubs/issues

**Comment by brahmnes** [comment]
Thanks @jakelandis !
