### ISSUE TITLE
Eventhub username/key should be renamed to indicate they are part of the shared access policy

### ISSUE THREAD

**Issue by andrewvc** [Azure/azure-diagnostics-tools#134]
Event hubs don't have user names, but rather 'shared_access_policies'.

After talking to @brahmnes we decided it'd be better to rename `username` to `access_policy_name`  and `key` to `access_policy_key`

**Comment by andrewvc** [comment]
We should also document where / how to get that value

**Comment by brahmnes** [comment]
Thanks @jakelandis !
