### ISSUE TITLE
Eventhub partition leasing

### ISSUE THREAD

**Issue by chriscoveyduck** [Azure/azure-diagnostics-tools#138]
When using this input is it possible to implement the receiver using a high level abstraction that allows leasing against the partitions?  Reason for the request is to be able to have multiple logstash instances subscribed to the event-hub both for load balancing and fault tolerance.

**Comment by brahmnes** [comment]
No solutions yet, but this is currently being looked at, possibly including the use of a Java EventProcessorHost library that abstracts the assignment of receivers to parititons.

**Comment by EmFl** [comment]
Hello,
I'm running something like this in production, looking at open sourcing it.

**Comment by brahmnes** [comment]
@EmFl 
Do you mean you are also using the Java EventProcessorHost, or you implemented something on your own that handles this?

**Comment by jakelandis** [comment]
`logstash-input-azureeventhub` has been superseded by `logstash-input-azure_event_hubs`

`logstash-input-azure_event_hubs` is implemented with EventProcessorHost API that allows for multiple Logstash instances work together and persist the offset between restarts. 

Note the options have changed and may be viewed [here](https://github.com/logstash-plugins/logstash-input-azure_event_hubs/blob/master/docs/index.asciidoc) until they are properly added to the standard documentation. 

To install the new plugin:
```
bin/logstash-plugin install logstash-input-azure_event_hubs
```

If issues are found with the new plugin please submit issues to : https://github.com/logstash-plugins/logstash-input-azure_event_hubs/issues

**Comment by brahmnes** [comment]
Hi @chriscoveyduck,

Please try Elastic's version of the eventhub input plugin
https://github.com/logstash-plugins/logstash-input-azure_event_hubs
