### ISSUE TITLE
Multi Reader Coordination

### ISSUE THREAD

**Issue by dgilling** [Azure/azure-diagnostics-tools#14]
For the logstash-input-azureeventhub, anyone knows of a plugin that can handle coordination a,omng multiple readers before I make one?

Something like jabb-core-java8 does a good job leveraging Azure Table storage without running your own ZooKeeper/Consul, etc.

**Comment by trondhindenes** [comment]
Shouldn't the eventhub consumer groups take care of this? I haven't tried, but if you setup multiple logstash instances using the same consumer group they should (in theory) never re-read the same events.

**Comment by yantang-msft** [comment]
@troettinger Consumer group won't do the work for you. You can always read the same data over and over again by giving the offset.
This post explained how to ensure only one consumer group at a time or have up to 5 concurrent readers.
https://blogs.msdn.microsoft.com/gyan/2014/09/02/event-hubs-receiver-epoch/
