### ISSUE TITLE
Question  can "logstash-input-azureblob" support a start date settings (so not look at logs before this date)

### ISSUE THREAD

**Issue by hassanbabaie** [Azure/azure-diagnostics-tools#141]
I'm running the logstash plugin to pull NSG Flow logs which are then forwarded over to a Graylog server however the issue is I have 6 months worth of logs in the storage account that we can't remove and so I think it might take about a month for the logstash to pull them all (running approx 500 logs per minute into Graylog. 

I've seen on other projects people have added start dates to reduce this impact and so I was wondering if this plugin can do the same and maybe understand the /y=2018/m=02/d=02/ string and so reduce the amount of history we pull in?

**Comment by brahmnes** [comment]
Not at the moment.
Here are some possibilities:
1. Copy just the blobs to another storage account, and then logstash pull from there instead
2. There is a registry file written by the azureblob plugin. You can hand-hack it so it blocks out the blobs you don't want it to process
3. Submit a PR to support this functionality. The functionality will be an additional parameter to specify an expression where the plugin processes only blobs with names matching that expression.

**Comment by hassanbabaie** [comment]
Thanks @brahmnes I'm not sure I have the skills to do a pull request for this, could I submit a new ticket for this as a feature..?

Thanks again

**Comment by brahmnes** [comment]
Sure

**Comment by hassanbabaie** [comment]
Thanks I'll get a new ticket in asap
