### ISSUE TITLE
Enhancement -  Add additional parameter for plugin to processes only blobs with names matching that expression

### ISSUE THREAD

**Issue by hassanbabaie** [Azure/azure-diagnostics-tools#142]
This is to supporting adding additional parameters for plugins to processes only blobs with names matching that expression.

Key is when pulling NSG logs having the option of a start date expression e.g. `*/y=2018/m=02/d=02/*` so that logs before this date are not processed. will drastically improve processing time in Logstash and then onto the reporting tool.

**Comment by brahmnes** [comment]
This issue is now addressed by https://github.com/Azure/azure-diagnostics-tools/pull/159 and released as 0.9.13
