### ISSUE TITLE
Question regarding stopping and resuming logstash

### ISSUE THREAD

**Issue by Thor-Kristian-Valderhaug** [Azure/azure-diagnostics-tools#144]
We are planning to use logstash-input-azureeventhub to propagate log messages from a azure eventhub into Elastic search.
The initial setup was smooth and log messages started showing up in elastic search.
However, I have one question regarding stopping and resuming the logstash instance.

From my testing it seems that the plugin does not store the timestamp of the last recived event.
Would it be possible to store this timestamp and read it at startup so that the plugin could pick up where it left off without missing events that occurred while logstash was stopped?

**Comment by brahmnes** [comment]
There is some plans on using the JavaEventProcessorHost, as mentioned in this issue:
https://github.com/Azure/azure-diagnostics-tools/issues/138

JavaEventProcessorHost can use an Azure storage blob to store this timestamp information so the plugin doesn't have to manage it.

**Comment by jakelandis** [comment]
`logstash-input-azureeventhub` has been superseded by `logstash-input-azure_event_hubs`

`logstash-input-azure_event_hubs` is implemented with EventProcessorHost API that allows for multiple Logstash instances work together and persist the offset between restarts. 

Note the options have changed and may be viewed [here](https://github.com/logstash-plugins/logstash-input-azure_event_hubs/blob/master/docs/index.asciidoc) until they are properly added to the standard documentation. 

To install the new plugin:
```
bin/logstash-plugin install logstash-input-azure_event_hubs
```

If issues are found with the new plugin please submit issues to : https://github.com/logstash-plugins/logstash-input-azure_event_hubs/issues

**Comment by brahmnes** [comment]
Hi @Thor-Kristian-Valderhaug,

Please try Elastic's version of the eventhub plugin
https://github.com/logstash-plugins/logstash-input-azure_event_hubs
