### ISSUE TITLE
[logstash-input-azurewadtable]: PartitionKey requirements

### ISSUE THREAD

**Issue by ypid-geberit** [Azure/azure-diagnostics-tools#146]
I tried to use [logstash-input-azurewadtable](https://github.com/Azure/azure-diagnostics-tools/tree/master/Logstash/logstash-input-azurewadtable) but it seems to have certain requirements on how the PartitionKey is used that are not documented. The plugin assumes that the PartitionKey is or ends with the timestamp (example: `0000000000000000007___0636547162800000000`). I can only find hints that this can be useful but the format seems to be nothing that everybody uses.

* https://docs.microsoft.com/en-us/azure/cosmos-db/table-storage-design-guide#log-tail-pattern
* https://alexandrebrisebois.wordpress.com/2014/06/16/using-time-based-partition-keys-in-azure-table-storage/

There have been other issues related to this question but all the answers there just assume that the PartitionKey is in a matching format:

* #112
* #71 

This issue is different from #43 in that this issue is about documentation and thought process of the current implementation.

It would be helpful to add a hint to the docs including a reference why this is best practice. Or am I missing something?

**Comment by brahmnes** [comment]
@ypid-geberit 
There is probably no good reasons why the format is different than others. A likely explanation is that these technology were developed separate at different times.

I also agree that this partition key scheme is not the best, but it's not something that can be changed easily because any change here would break all existing tools. The code here shows how it's related to the timestamp
https://github.com/Azure/azure-diagnostics-tools/blob/master/Logstash/logstash-input-azurewadtable/lib/logstash/inputs/azurewadtable.rb#L189

**Comment by ypid-geberit** [comment]
@brahmnes 

Thanks for the explanation!

About changing the code, the plugin could just support multiple schemes and make them configurable. But #43 is more about this topic.

**Comment by brahmnes** [comment]
@ypid-geberit 
Agree with your statement. Perhaps an extra parameter to configure which scheme to use.
Do you want to submit a PR?

**Comment by ypid-geberit** [comment]
@brahmnes We decided to go with the currently supported scheme for now and would still be interested in the background of the current schema and some more documentation (ideally in the plugin docs – You don’t have to answer to comment, a URL to the plugin docs would be sufficient). The `0000000000000000007` (`0..99`) in `0000000000000000007___0636547162800000000` is just for distribution of rows in the distributed table storage?

**Comment by brahmnes** [comment]
@ypid-geberit 
I am not aware of docs elsewhere, so I added some information in the README in this repo:
https://github.com/Azure/azure-diagnostics-tools/tree/master/Logstash/logstash-input-azurewadtable

I also don't know the full history or reasoning behind this format, but I hope this should be enough to understand the different pieces of the key.
