### ISSUE TITLE
Logstash input azurewadtable

### ISSUE THREAD

**Issue by DwijadasDey** [Azure/azure-diagnostics-tools#147]
Hi
I am trying to fetch data from azure storage table using the following config.

```
input {
        azurewadtable
                 {
                   account_name => "AccountName"
                   access_key => "My_Key"
                   table_name => "Table_Name"
        }
}

output {
        stdout
               {
                  codec => rubydebug
               }

        elasticsearch
               {
                  index => "storage-%{+dd.MM.YYYY}"
                  hosts => ["localhost:9200"]
               }
}
```
In the logstash debug output, I can see the following but no output to the elastcisearch.

```
[2018-02-26T15:39:41,238][DEBUG][logstash.inputs.azurewadtable] collection time parsed successfully 2018-02-26 15:38:40 +0000
[2018-02-26T15:39:41,238][DEBUG][logstash.inputs.azurewadtable] Converting time to ticks
[2018-02-26T15:39:41,239][DEBUG][logstash.inputs.azurewadtable] 0' and PartitionKey lt '0000000000000000077___0636552562800000000') or 
(PartitionKey gt '0000000000000000023___0123456789000000000' and PartitionKey lt '0000000000000000023___0123456789000000000') or (PartitionKey gt '00000000
[2018-02-26T16:15:44,610][DEBUG][logstash.inputs.azurewadtable] No new results found.
```

Logstash could connect to the storage table but there is no data in the ES or in the file. Shall i have to write query in filter section ?

**Comment by DwijadasDey** [comment]
Hi
Brahmnes
I don't see any query log being generated in the debug output of logstash.
Regards

**Comment by brahmnes** [comment]
I was suggesting to modify the plugin code and trace out what the query string looks like.
Basically diagnosing whether data was actually read by from the table into logstash.

Checking Azure storage explorer helps in seeing if any data is actually there.
If the query looks right and the data is there, but it's not getting read, then it's a problem in azure storage sdk.

**Comment by DwijadasDey** [comment]
I checked the plugin code () and found the following line ->

```
def run(on_result_cbk)
    results_found = false
    @logger.debug("[#{@query_id}]Query filter: " + @query_str)
begin
      @logger.debug("[#{@query_id}]Running query. continuation_token: #{@continuation_token}")
.................
.................
```
But i did not find any line in logger debug like **Query filter:** query string value but the next logger statement is there in the debug output.

`[2018-02-27T03:01:34+00:00-2018-02-27T03:02:44+00:00]Running query. continuation_token: `

Also there is no line in the debug output that corresponds to following line.
 @logger.debug("[#{@query_id}] #{result.length} results found.")

Does that means the query did run but there is no data ?

**Comment by brahmnes** [comment]
That's right. It's not picking up anything. That's why I am saying, check the query and check your storage to see why it's not picking up data.

**Comment by DwijadasDey** [comment]
Logstash can connect to the table but accessing https://myac.table.core.windows.net/Tables('table_name') results in ResourceNotFound.

I don't have access to the azure storage settings. But does "ResourceNotFound." means the table does not exists ? If it does not exists then why logstash is not throwing 404 error as is evident from changing the table name to a non existent one in the logstash config results in a 404 error.

**Comment by DwijadasDey** [comment]
Please ignore the last comment as we can't directly browse table storage like typing the table storage endpoint in browser window.

**Comment by DwijadasDey** [comment]
I have the PartitionKey value equal to 1 for all rows in the storage table and Logstash is running query filter like 

`(PartitionKey gt '0000000000000000023___0123456789000000000' and PartitionKey lt '0000000000000000023___0123456789000000000') or (PartitionKey gt '00000000..............)`

The above line in the debug log is from the function build_latent_query or build_zero_latency_query function (azurewadtable.rb).  The query executed but does not find any matches in the table.

If i remove `:filter => query_filter` from the process function in the query parameter then logstash can fetch the data although it runs infinitely with no data being transferred to ES.

Whether timestamp format in source code (collection_start_time_utc) can be changed to servers timestamp ?

**Comment by brahmnes** [comment]
This plugin accepts data outputted by WAD (Windows Azure Diagnostics) agent.
The partition key cannot be just 1 and removing the filter will not work. I added a comment in https://github.com/Azure/azure-diagnostics-tools/issues/71 to indicate what formats it expects and why the code accepts these.

I am not sure what you mean by server timestamp.

**Comment by DwijadasDey** [comment]
You are Right ! The partition key cannot be just 1. Even if i changed the query filter in the source code by commenting the loops and adding new conditions and that makes logstash received the data from the table but i can see in the debug console that logstash runs in a loop and fetch the same data again and again. Although i have removed the duplicate entries by adding document id in the ES output section. But that does not make logstash stops processing the same data again and again.

Partition key without timestamp will make logstash very in-efficient and there is no substitute for key with timestamp for PartitionKey column. May be in the future release we will be able to pass parameters in input section of logstash config specifying conditions.

Server timestamp => Can we change the format timestamp in the source code ? `(collection_start_time_utc)`

Thanks again for all replies.
Regards

**Comment by brahmnes** [comment]
This plugin was designed to read data produced by Windows Azure Diagnostics (WAD) agent. That's why it doesn't support custom timestamp format.

I can see it being parameterized to support reading data produced by Azure App Service. If you want to submit a PR, we can take a look.
