### ISSUE TITLE
Feature request: Watch specific files/directories in azureblob plugin

### ISSUE THREAD

**Issue by nymous** [Azure/azure-diagnostics-tools#158]
When using the `logstash-input-azureblob` plugin, we can only specify the blob storage to watch, then all files inside will be read. When said blob is used to store both input data, output results and logs, it brings in way too much junk, which we can't filter in Logstash because we don't have access to the original filename.

It would be great if we could specify which files to read, in a way similar to the `file` input plugin:
```
input
{
    azureblob
    {
        storage_account_name => "mystorageaccount"
        storage_access_key => "VGhpcyBpcyBhIGZha2Uga2V5Lg=="
        container => "mycontainer"
        path => [ "/path/to/logs/*.log" ]
    }
}
```

**Comment by nymous** [comment]
Actually I see now that fixing #103 would work around this. But if we can choose which files to pull it would be even better 😄

**Comment by nymous** [comment]
I am looking at the implementation, but sadly there is no way in `Container#list_blobs` to filter with anything but a prefix.
Our use case requires jokers, to match `*/driver/log4j-*.log`. Should I list all blobs in the container, and then filter the matching blobs according to their names (which contains the full path to the blob)?

**Comment by brahmnes** [comment]
Hi @nymous,

Yes, filtering on the matching blobs would be fine. You can add a regular expression as a parameter, and if this parameter is not specified, then no filtering is done. This won't break existing clients and it's nothing worse than what we have today.

Looking at the code again, this may be a better place to perform the filtering:
https://github.com/Azure/azure-diagnostics-tools/blob/master/Logstash/logstash-input-azureblob/lib/logstash/inputs/azureblob.rb#L327

That way the registry path won't get accidentally filtered out by the regular expression.

**Comment by brahmnes** [comment]
Hi @nymous,

Your approach looks reasonable. Feel free to submit a PR.
I can't say much about the quirks that you are encountering. It may be best to refer to logstash documentations for best development practices.

**Comment by nymous** [comment]
PR is in and CLA is signed! Sorry for the delay!
