### ISSUE TITLE
Logstash configuration for the Azure Activity Logs.

### ISSUE THREAD

**Issue by Shri-Harsha** [Azure/azure-diagnostics-tools#164]
I need a way to pull the Azure activity logs in to the Logstash and Parse them. Can any body provide the .conf file for that use case?

**Comment by brahmnes** [comment]
Hi @Shri-Harsha,

There is currently no plugins that directly pull data from Azure activity logs and put into Logstash. You can however export them to eventhub, and then use https://rubygems.org/gems/logstash-input-azure_event_hubs to ingest them. The github repo for this plugin is at https://github.com/logstash-plugins/logstash-input-azure_event_hubs
