### ISSUE TITLE
Faraday connection failed errors in azuretopicthreadable

### ISSUE THREAD

**Issue by watsonlu** [Azure/azure-diagnostics-tools#166]
Hey guys,

I'm running the azuretopicthreadable plugin on top of the elasticsearch logstash:6.3.2 container. I'm basically doing 

`/usr/share/logstash/bin/logstash-plugin install logstash-input-azuretopicthreadable`

with no other modifications.

whenever I run the container, I'm getting these errors

```
[2018-08-27T19:24:49,098][ERROR][logstash.inputs.azuretopicthreadable] Oh My, An error occurred. Thread id:3 {:exception=>#<Faraday::ConnectionFailed>}
[2018-08-27T19:26:19,358][ERROR][logstash.inputs.azuretopicthreadable] Oh My, An error occurred. Thread id:20 {:exception=>#<NoMethodError: undefined method `reason_phrase' for #<Faraday::Response:0x5555fa72>>}
```

for basically every thread. 

My inputs looks like this:

` 
azuretopicthreadable
         {

             namespace => "namespace1"

             access_key_name => "Logstashk8"

             access_key => "mysaskey"

             subscription => "Logstash-k8-sub"

             topic => "topic4"

             type => "dev-application-logs"

             threads => 32

             thread_sleep_time => 10

         }

         azuretopicthreadable

         {

             namespace => "namespace1"

             access_key_name => "Logstashk8"

             access_key => "mysaskey"

             subscription => "Logstash-k8-sub"

             topic => "topic3"

             type => "prod-application-logs"

             threads => 64

             thread_sleep_time => 10

         }

         azuretopicthreadable

         {

             namespace => "namespace1"

             access_key_name => "Logstashk8"

             access_key => "mysaskey"

             subscription => "Logstash-k8-sub"

             topic => "topic2"

             type => "prod-application-logs"

             threads => 64

             thread_sleep_time => 10

         }

         azuretopicthreadable

         {

             namespace => "namespace1"

             access_key_name => "Logstashk8"

             access_key => "mysaskey"

             subscription => "Logstash-k8-sub"

             topic => "topic1"

             type => "dev-application-logs"

             threads => 32

             thread_sleep_time => 10
         }
`

some messages ARE getting in though, but not a lot. I checked the gems and they're all there, and the plugin installs successfully.

**Comment by brahmnes** [comment]
Hi @watsonlu, 

This issue looks the same as this one:
https://github.com/Azure/azure-diagnostics-tools/issues/135

It happens where there is an error with the config, and then when it's trying to get the reason_phrase which will tell why it failed, it failed again.
In that github issue, the suggested workaround was to modify the dependency so it depends on a newer version of a package, but we never figured out how to just modify a ruby file at the install location and make it work.

**Comment by watsonlu** [comment]
I figured it out, it ended up being a SAS key mistake on my end. Incredibly annoying to debug though.

However to debug it I figured out a way to get the azure core gem to output logs that don't suck.

Things that don't work:

1. Installing the azure-core gem, editing the http_response file and checking the logstash logs
2. Installing the azure-core gem, editing the http_response file, rebuilding the gem and installing the local gem thats been built

I don't think the code posted in that issue fixes the error message issue, I even went as far as to put console outputs in that method and still got them along with the useless exceptions.

The only way I found to fix it is:

1. On the logstash server, uninstall the logstash plugin
2. On the logstash server, uninstall the azure-core gem using `gem uninstall azure-core`
3. I'd also suggest checking the gem folder on the server to make sure that the gem is completely gone.
3. Clone the azure-ruby-asm-core gem
4. go into the gemspec and change the faraday runtime requirements the latest version, so right now thats:

  ` s.add_runtime_dependency('faraday',                 '~> 0.15') `
  ` s.add_runtime_dependency('faraday_middleware',      '~> 0.12') `

5. gem build azure-core.gemspec
6. Copy the gem to the server, then do `gem install azure-core --local` in the same folder as the gem
7. Install the service bus logstash plugin as normal

After that the plugin should work the same, but spit out actual useful errors logs.

I'm running the modified core gem in staging and it seems fine so far, so I don't think swapping bag to the prod gem after debugging your config is necessary.

Note that if you're running logstash in the offical logstash container, you need to run `ruby -s gem` before every gem command ran in the server.

**Comment by brahmnes** [comment]
Hi @watsonlu,

Thank you for contributing the steps to work around this problem! Glad to hear that you were able to nail the root problem.
