### ISSUE TITLE
path_filters uknown setting

### ISSUE THREAD

**Issue by camilisette** [Azure/azure-diagnostics-tools#171]
I am getting an error when using "path_filters" 

[2018-09-25T10:12:01,998][ERROR][logstash.inputs.logstashinputazureblob] Unknown setting 'path_filters' for azureblob

logstash-input-azureblob (0.9.12)

I already updated the plugin using "logstash-plugin update logstash-input-azureblob"

How do I fix this?

**Comment by brahmnes** [comment]
Hi @camilisette,

That's because version 0.9.12 doesn't have that feature yet.
Version 0.9.13 has just been released and it has this fix. Please try again.
