### ISSUE TITLE
Logstash input for Azure blob - HTTPError: Caught exception while locking

### ISSUE THREAD

**Issue by frode** [Azure/azure-diagnostics-tools#18]
Caught exception while locking {:exception=>#<Azure::Core::Http::HTTPError: BlobTypeNotSupported (400): Page blob is not supported for this account type.
RequestId:01094fce-0001-0003-44a2-c71ed5000000

I have two environments set up with ELK, both located in North Europe.

Environment 1: Read access Geo-redundant storage (says it is available both west and north europe)
Environment 2: Zone redundant storage

1: Works fine, data is stored in blob blocks
2: Does not work, data is also stored in blob blocks, but the error is related to blob type?

Anyone know if i can log more info that makes more sense in this scenario?

Config for them both are identical with input and output.

00_input.conf:

input
{
 azureblob {
   storage_account_name => "environment1"
   storage_access_key => "environment1key"
   container => "logs"
  }
}

10_output.conf:

output {
      stdout {
                codec => "json"
            }
             elasticsearch {
               hosts => ["10.0.2.100:9200"]
               user => "es_username"
               password => "espassword"
            }
}

Starting logstash with these parameters:
/opt/logstash/bin/./logstash -v -f /etc/logstash/conf.d/

-Frode

**Comment by Nordes** [comment]
As you've said it, I think it is due to the blob type. See ref.: https://msdn.microsoft.com/en-us/library/azure/ee691964.aspx

> ...Page blobs are a collection of 512-byte pages optimized for random read and write operations....

In my fork, I've added some more log info and changed the way it was reading using a "sincedb". But I need to test it with page blob.

**Comment by joaom182** [comment]
@frode Did you solved this issue?

**Comment by Yaswanth-C** [comment]
@frode Did anyone resolved this issue?

**Comment by frode** [comment]
Sorry, we abonded the logstash solution and I never did any follow up here.

**Comment by xiaomi7732** [comment]
@frode,
Sorry to hear that. We wish you had found a solution that fits.
Anyway, we rolled out a new implementation that (0.9.8) does not require page-blobs.
In case you still want to give it a try: https://rubygems.org/gems/logstash-input-azureblob.
