### ISSUE TITLE
Why plugin logstash-input-azureblob is not installed by default as  logstash-input-azure_event_hubs

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-diagnostics-tools#197]
I'm going to use this plugin and notice that it is not installed by default in logstash:

`bin/logstash-plugin list`

> logstash-input-azure_event_hubs
> logstash-input-beats
> logstash-input-couchdb_changes
> logstash-input-dead_letter_queue
> logstash-input-elasticsearch
> ...

Is it possible to install it by defaultlike `logstash-input-azure_event_hubs`?

**Comment by briangardner** [comment]
I'm guessing this is because Elastic has taken over ownership of the event_hubs plugin, but they have not taken ownership of the azureblob plugin.
