### ISSUE TITLE
jar dependencies found on non-java platform gem - do not install jars

### ISSUE THREAD

**Issue by EmFl** [Azure/azure-diagnostics-tools#2]
Hello,
I'm trying to install this but even though I can do a simple
sudo /opt/logstash/bin/plugin install logstash-input-azureeventhub
and I get this : 
Validating logstash-input-azureeventhub
Installing logstash-input-azureeventhub
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
jar dependencies found on non-java platform gem - do not install jars
Installation successful

Then using something like this : 
input {
        azureeventhub {
                namespace => "eventhubnamespace"
                key => "mykey"
                username => "eventhubsharedaccesspolicyname"
                eventhub => "eventhubname"
                partitions => "4"
        }
}
I get this in the log :
{:timestamp=>"2016-04-14T15:13:33.530000+0000", :message=>"The error reported is: \n  Couldn't find any input plugin named 'azureeventhub'. Are you sure this is correct? Trying to load the azureeventhub input plugin resulted in this error: no such file to load -- geronimo-jms_1.1_spec-1.1.1"}

I've also tried to run 
$:~/azure-diagnostics-tools/Logstash/logstash-input-azurewadeventhub$ sudo  env GEM_HOME=/opt/logstash/vendor/bundle/jruby/1.9 /opt/logstash/vendor/jruby/bin/jruby /opt/logstash/vendor/jruby/bin/gem build ./logstash-input-azureeventhub.gemspec
$:~/azure-diagnostics-tools/Logstash/logstash-input-azureeventhub$ sudo /opt/logstash/bin/plugin install ./logstash-input-azurewadeventhub-0.9.4.gem

But the result is the same.
I also tried creating that directory 
/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureeventhub-0.9.4/vendor/jar-dependencies/runtime-jars
and pushing the jar in that folder (retrieved from : http://central.maven.org/maven2/org/apache/geronimo/specs/geronimo-jms_1.1_spec/1.1/geronimo-jms_1.1_spec-1.1.jar)
But I still get the same error message.

Any pointer would be appreciated.
Thanks

**Comment by brahmnes** [comment]
What version of logstash are you using?
I have also seen this error. If the jar files are not deployed by logstash, this can be worked around by dropping these jar files in the /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureeventhub-0.9.4/lib directory

geronimo-jms_1.1_spec-1.1.1.jar
qpid-amqp-1-0-client-jms-0.32.jar
qpid-amqp-1-0-common-0.32.jar
qpid-amqp-1-0-client-0.32.jar

The azurewadeventhub plugin is specifically for parsing Windows Azure Diagnostics data written to eventhub. It's not yet published to rubygems.org, but it will be.

**Comment by EmFl** [comment]
Hello,
Thanks, I didn't push the jar in the correct folder. Having installed the gems locally I had to open /opt/logstash/Gemfile and then look at the local path specified, this resulted in pushing jar file to : /opt/logstash/vendor/local_gems/2a80296c/logstash-input-azurewadeventhub-0.9.4/lib

However I seem to encounter yet another issue, now that the azurewadeventhub is starting, I'm getting this in the log : 
{:timestamp=>"2016-04-18T07:44:40.818000+0000", :message=>"  01 --- Error: Unable to JSON parse '{\"records\":[{\"dimensions\":{\"DeploymentId\":\"c985a89f1ba8456fa7bb82037\",\"Role\":\"IaaS\",\"RoleInstance\":\"myvm\"},\"last\":404,\"metricName\":\"\\\\Memory\\\\Available MBytes\",\"time\":\"2016-04-18T07:44:35.1619362Z\",\"timeGrain\":\"PT180S\"}]}'.", :exception=>#<NameError: uninitialized constant LogStash::Inputs::Azurewadeventhub::JSON>, :level=>:error}

**Comment by EmFl** [comment]
Fixed this error by adding a require "json" in  azurewadeventhub.rb and restarting logstash.
Now getting my event in elasticsearch yay !

**Comment by brahmnes** [comment]
Glad that you found the cause of the problem.
Some versions of ruby seem to not require the require statement for json. We will look into the issue and see if we should add require 'json'.
