### ISSUE TITLE
logstash-output-applicationinsights latest needs to be pushed to RubyGems

### ISSUE THREAD

**Issue by 163satish** [Azure/azure-diagnostics-tools#218]
The gemspec has not been modified since Feb 2017. There was a fix that was made to the [applicationinsights.rb](https://github.com/Azure/azure-diagnostics-tools/blob/master/Logstash/logstash-output-applicationinsights/lib/logstash/outputs/applicationinsights.rb) and the gemspec was not been upgraded to next version: [azure-diagnostics-tools/Logstash/logstash-output-applicationinsights/logstash-output-applicationinsights.gemspec](https://github.com/Azure/azure-diagnostics-tools/blob/master/Logstash/logstash-output-applicationinsights/logstash-output-applicationinsights.gemspec)

Please upgrade the version and release to [RubyGems](https://rubygems.org/gems/logstash-output-applicationinsights/).

**Comment by brahmnes** [comment]
Hi @163satish,

Version 0.9.3 has been published. Please try it out.
https://rubygems.org/gems/logstash-output-applicationinsights

**Comment by 163satish** [comment]
Thank you @brahmnes  for pushing it. I will check.
