### ISSUE TITLE
Occasional undefined method `iso8601' error from logstash-input-azurewadtable

### ISSUE THREAD

**Issue by jstangroome** [Azure/azure-diagnostics-tools#22]
Running Logstash 2.3.2 on Ubuntu 14.04 the following error will occassionally appear in the `logstash.log`:

{:timestamp=>"2016-07-24T12:25:21.834000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::AzureWADTable account_name=>\"REDACTED\", access_key=>\"REDACTED\", table_name=>\"LinuxDiskVer2v0\", codec=><LogStash::Codecs::Plain charset=>\"UTF-8\">, entity_count_to_process=>100, collection_start_time_utc=>\"2016-07-22T07:51:23Z\", etw_pretty_print=>false, idle_delay_seconds=>15, endpoint=>\"core.windows.net\">\n  Error: undefined method `iso8601' for nil:NilClass", :level=>:error}
{:timestamp=>"2016-07-24T13:12:55.889000+0000", :message=>"Oh My, An error occurred.", :exception=>#<NoMethodError: undefined method`iso8601' for nil:NilClass>, :level=>:error}

I suspect the code isn't dealing with some entities having an undefined TIMESTAMP field.

https://github.com/Azure/azure-diagnostics-tools/blob/fde74437bbaa70bb67b9343138688d9a00307d24/Logstash/logstash-input-azurewadtable/lib/logstash/inputs/azurewadtable.rb#L100

**Comment by brahmnes** [comment]
You are probably correct. The linux diagnostics agent should be writing valid TIMESTAMP every time, so it's unclear why that can happen.
The plugin can probably be more resilient by collecting the TIMESTAMP field for each row and pick the  last known good one. Would that work for you?

**Comment by jstangroome** [comment]
That seems like a reasonable solution.

**Comment by brahmnes** [comment]
logstash-input-azurewadtable 0.9.11 with the fix is now available on rubygems.org
