### ISSUE TITLE
Request to add decorate() so we can use types/tags

### ISSUE THREAD

**Issue by darkshade9** [Azure/azure-diagnostics-tools#24]
Requesting the ability to tag and type inputs so that we have the ability to key against them to organize outputs, i.e. a different ES index per input.  Currently, setting a type or tag via input gets stripped.

Examples:
https://github.com/elastic/logstash/blob/master/logstash-core/lib/logstash/inputs/base.rb#L98
https://github.com/logstash-plugins/logstash-input-file/blob/master/lib/logstash/inputs/file.rb#L300

Thanks

**Comment by kalim81** [comment]
Second this, really required for this plugin

**Comment by darkshade9** [comment]
@kalim81 This is what I did in the meantime:

Setup a filter to parse the message into json, then grab a field you want to separate indexes on, i.e. UserName:

            ```
json {
                source => "message"
            }

            if [UserName] =~ /USERNAME$/ {
                    mutate {
                            add_field => { "type" => "TYPE" }
                    }
            } else {
                    mutate {
                            add_field => { "type" => "OTHERTYPE" }
                    }
            }
        }
```

**Comment by kalim81** [comment]
Thanks @darkshade9. I had tried to make the conditional check based on the event hub key but without json parse, will try this.

**Comment by EmFl** [comment]
I've just submitted a pull request exactly for this #34

**Comment by brahmnes** [comment]
The plugins have been updated on rubygems.org with this PR.
