### ISSUE TITLE
The error reported is:   can't convert nil into String

### ISSUE THREAD

**Issue by wenboyang214** [Azure/azure-diagnostics-tools#29]
I am new to Logstash plugin. facing the error of 'can't convert nil into String' when  configuration  testing 

really have no idea and need some help.

thanks

**Comment by yantang-msft** [comment]
@wenboyang214 Try StdOutput with codec => rubydebug, and see where it tries to convert nil to string

**Comment by wenboyang214** [comment]
thanks @yantang-msft . I have done what you said .but still  the same error . like below:

An unexpected error occurred! {:error=>#<TypeError: can't convert nil into String>, :class=>"TypeError", :backtrace=>["org/jruby/RubyKernel.java:1042:in `require'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-azureeventhub-0.9.5-java/lib/logstash/inputs/azureeventhub.rb:9:in `(root)'", "org/jruby/RubyKernel.java:1040:in `require'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/plugin.rb:1:in `(root)'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/plugin.rb:80:in `lookup'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/pipeline.rb:403:in `plugin'", "org/jruby/RubyKernel.java:1079:in `eval'", "(eval):7:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/pipeline.rb:60:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/agent.rb:171:in `execute'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/runner.rb:90:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/runner.rb:95:in `run'"], :level=>:warn}

what is wrong with my conditions. thanks for the help.

**Comment by yantang-msft** [comment]
@wenboyang214 How do you install azureevnethub input?
Can you share your configuration file as well?

**Comment by wenboyang214** [comment]
@yantang-msft  

input
{
    azureeventhub
    {	
        domain => "servicebus.chinacloudapi.cn"
        key => "mykey"
        username => "myusername"
        namespace => "mynamespace"
        eventhub => "myeventhub"
        partitions => 4
    }
}
output {
  stdout { codec => rubydebug }
}

I install it buy bin/plugin install logstash-input-azureeventhub

I trend to think my logstash version (2.2) was too high for this plugin?
so reduced version to  1.5    and  trying on the way.

**Comment by wenboyang214** [comment]
@yantang-msft   thanks for your help . I have solved some issue by the help of https://github.com/Azure/azure-diagnostics-tools/issues/2

But I am still  facing the issue

when I get message from eventhub in global Azure. it was correct.  but when I get message from

eventhub in Azure  China .it went wrong even though setting the domain  with "servicebus.chinacloudapi.cn". 

any suggestions? thanks for you answer again.

**Comment by yantang-msft** [comment]
@wenboyang214 I just tested this plugin. Similar to your case, it works with event hubs created in public Azure but not Azure China.
A good news is it's just a SSL certificate issue, and the error message looks like this "javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target".

I finally get it to work by following the links below. Hope it can solve your problem.
https://confluence.atlassian.com/kb/unable-to-connect-to-ssl-services-due-to-pkix-path-building-failed-779355358.html
https://confluence.atlassian.com/kb/connecting-to-ssl-services-802171215.html

**Comment by wenboyang214** [comment]
@yantang-msft  Oh. thanks for the help . I will have a try.
