### ISSUE TITLE
logstash-input-azureblob in China Azure.

### ISSUE THREAD

**Issue by wenboyang214** [Azure/azure-diagnostics-tools#30]
I am in the trouble of using logstash-input-azureblob in China Azure. 

when running I got the error 'Oh My, An error occurred. {:exception=>#<Faraday::ConnectionFailed>, :level=>:error}

when using logstash-input-eventhub  I can set the domain to 'servicebus.chinacloudapi.cn'  then I get data for eventhub in China Azure successfully.

I wonder how I can get data with the none setting domain logstash input plugin such as above mentioned.

**Comment by yantang-msft** [comment]
@whiskeyjay There should be an endpoint parameter, which is not exposed as a parameter currently.

**Comment by yantang-msft** [comment]
Hey Jay,

Could you please take a look at this issue and provide a simple fix?

Thanks!
Yanming

**Comment by wenboyang214** [comment]
@yantang-msft  thanks  a lot. 

may I have the idea that  the endpoint has been fixed down in the azure-sdk-for-ruby? I try  to find out where the endpoint has been fixed down. but failed.

**Comment by yantang-msft** [comment]
It's not the azure-sdk-for-ruby, but this one https://rubygems.org/gems/azure
Search for "core.windows.net" among the files to get started digging into the library.

**Comment by wenboyang214** [comment]
@yantang-msft  OK  thanks I will have a try

**Comment by yantang-msft** [comment]
@wenboyang214 The pull request is sent out. Please give it a shot.

**Comment by wenboyang214** [comment]
@yantang-msft @whiskeyjay 

Thanks

**Comment by whiskeyjay** [comment]
@wenboyang214 Please let us know how the change works for you. If it looks good, we'll merge the PR.
Thanks!

**Comment by wenboyang214** [comment]
@whiskeyjay I can connect to the blob in Mooncake  thanks for you help.
