### ISSUE TITLE
Modify for China Azure

### ISSUE THREAD

**Issue by wenboyang214** [Azure/azure-diagnostics-tools#32]
Hi @karolz-ms

Thanks for the plugin for the Logstash plugin tool .

Also I aspire to use the logstash plugin in China Azure. could you add the configuration for  logstash plugin tool so that it can be suitable to China Azure.

I can configure the eventhub endpoint. but others not.

thanks.

**Comment by brahmnes** [comment]
logstash-input-azurewadtable 0.9.11 is now available on rubygems.org. It exposes a endpoint parameter which lets you reconfigure it for China Azure.

Which set of plugins do you need to configure endpoints?
