### ISSUE TITLE
Not getting information from WADLogsTable

### ISSUE THREAD

**Issue by lspanke** [Azure/azure-diagnostics-tools#33]
Have configured multiple inputs, and some tables are coming in, but nothing is coming from the WADLogsTable

**Comment by brahmnes** [comment]
Are you still hitting the issue? The azurewadtable plugin by default skips all rows with a timestamp before the time when the plugin starts running. If in doubt, you can set the collection_start_time_utc parameter to something earlier to see if it picks up those rows. Or just write something new to it after the plugin starts.

**Comment by brahmnes** [comment]
Closed due to no response.
