### ISSUE TITLE
Azure::Core::Http::HTTPError: LeaseIdMissing

### ISSUE THREAD

**Issue by darkshade9** [Azure/azure-diagnostics-tools#41]
I've been getting this error popping up infrequently in my Logstash log file:

`{:timestamp=>"2016-09-21T15:04:10.602000+0000", :message=>"Caught exception while locking", :exception=>#<Azure::Core::Http::HTTPError: LeaseIdMissing (412): There is currently a lease on the blob and no lease ID was specified in the request.
RequestId:bb8b790c-0001-00ea-5619-14374e000000
Time:2016-09-21T15:04:10.7943321Z>, :level=>:error}
`

Plugin was built in version 0.9.6 from source to take advantage of the **decorate(event)** update

Any ideas?

**Comment by xiaomi7732** [comment]
@darkshade9,
Sorry to hear that.
1. Could you please clarify what is the plugin are you using?
2. Could you please making user the log file you are reading is not leased by other client already?

**Comment by xiaomi7732** [comment]
@darkshade9,
In the version of 0.9.8, we change the way of leasing to reduce chance of invalid leasing. Please give a try:
https://rubygems.org/gems/logstash-input-azureblob
