### ISSUE TITLE
JSON Parsing error when log string contains escape character

### ISSUE THREAD

**Issue by leewadhams** [Azure/azure-diagnostics-tools#42]
When the Event text contain an escaped character such as \n\r the input plugin is encoding the backslash character as hex to \x5c. The json parsing is then failing due to the fact that \x isn't a valid escape sequence in JSON.

Example event data:

``` javascript
{ "comments": "hello lee\n\rthis is another line", "age": 104 }
```

**Comment by EmFl** [comment]
Hello,
Are you using eventhub input by any chance ? 
This is how I fixed it for now :  #40

**Comment by darkshade9** [comment]
I have the same problem, I had to resort to gsubbing out the characters, i.e.

`                ruby {
                        code => " if event['message']
                        event['message'] = event['message'].gsub('\\x5c','\\')
                        end
                        "
                }
`

and

`                        mutate {
                                gsub => [ 'RenderedMessage','\"','"']
                        }
`

**Comment by brahmnes** [comment]
This should be handled in both azurewadeventhub and azureeventhub plugins. If you are seeing the behavior in another plugin, or it's not solving your issue, please reopen.
