### ISSUE TITLE
Better way to "start over"

### ISSUE THREAD

**Issue by gmanrodt** [Azure/azure-diagnostics-tools#44]
I made some changes to my import config, so I needed to reparse my log files (a few days worth). Since this plugin creates a *.log.lock file for each log file in BLOB storage, so that logstash knows where it left off, it is very tedious to tell logstash to start over and reparse the files. I wrote a quick recursive app to go through my blob storage and delete thees files, but I think there should be a better way to track where logstash left off.

**Comment by EmFl** [comment]
I suggest looking at Nordes fork : https://github.com/Nordes/azure-diagnostics-tools/blob/master/Logstash/logstash-input-azureblob/lib/logstash/inputs/azureblob.rb
This creates an azure storage table and writes the blobs and the last byte read and then start from that. If you want to start over, you should be able to simply drop the table and restart logstash (and also set correctly the ignore_older parameter

**Comment by xiaomi7732** [comment]
@gmanrodt,
Thanks for your suggestion. We have a new implementations.

Please refer the readme, making use of the new parameters of `interval` and `registry_create_policy`:
https://github.com/Azure/azure-diagnostics-tools/blob/master/Logstash/logstash-input-azureblob/README.md
