### ISSUE TITLE
logstash-input-azureeventhub stops checking eventhub

### ISSUE THREAD

**Issue by kalim81** [Azure/azure-diagnostics-tools#45]
For a while now we have noticed that the plugin stops listening to azure event hub. The occurrence is inconsistent! It could run fine for 30 hours but then stop listening or it could stop listening within 30 minutes of the logstash service being started. There are no errors written to the logs or anything that could relate to an issue.  Running in debug mode does not result in any error/warning being logged to why it stopped checking the azure event hub. The logstash service continues to run. The only solution is to restart the service which is not ideal!

I have tried running logstash both on Windows and Redhat OS's and the issue occurs in both. I am running the VM's in Azure.

Anyone else had this issue?

**Comment by EmFl** [comment]
Hello, 
I have probably had the same issue last week. Didn't investigate yet but will update this issue if I get the time. Please let me know if you find anything meanwhile.

**Comment by darkshade9** [comment]
I have this problem frequently.  We're likely moving onto our own EventHub reader that pushes into ELK, this one has too many problems.

**Comment by kalim81** [comment]
@darkshade9 Is it a logstash plugin you are developing or a bespoke solution? Would it be open sourced? Am looking at alternative options i.e. Redis Cache

**Comment by darkshade9** [comment]
@kalim81 One of our devs is writing a C# console app EH client, it spawns a thread per partition, calls the EH client code and reads from the queue.  The data is batched up and sent directly to ES.  Placeholder of which logs have been sent is stored in the application, so duplication is eliminated.  I'll see if we can open source it.

**Comment by EmFl** [comment]
hello @darkshade9, Just checking if you had any news about the app you mentionned ? Could probably be useful for one of my use case.
Thanks!

**Comment by darkshade9** [comment]
Hello!

I haven't forgotten about everyone :)  I'm going to speak with the dev and
his supervisor to find out the company policy on releasing this code as
open source.  If so, I'll post a link here in this issue to it and open it
up to the public.

**Comment by clguimanMSFT** [comment]
@kalim81 
Please verify with the latest master build. You need to checkout the code, then from the plugin folder build and install:
```
gem build logstash-input-azureeventhub.gemspec
sudo /usr/share/logstash/bin/logstash-plugin install ./logstash-input-azureeventhub-0.9.8-java.gem
```

**Comment by clguimanMSFT** [comment]
The issue should be fixed with v. 0.9.8.
