### ISSUE TITLE
logstash version 5.0.0

### ISSUE THREAD

**Issue by kedigby** [Azure/azure-diagnostics-tools#46]
I'm trying to use the logstash-input-azureeventhub, but appear to have a versioning issue. Is there much work involved in upgrading from version 2.0 to 5.0 ?

Error Message:

```
In snapshot (Gemfile.lock):
    logstash-core (= 5.0.0)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.0.0) java

    logstash-input-azureeventhub (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core (>= 0) java

```

**Comment by andrewvc** [comment]
Hi, I'm on the Logstash team! For most plugins upgrading is straightforward. Please read: https://www.elastic.co/guide/en/logstash/current/breaking-changes.html#_ruby_filter_and_custom_plugin_developers

Once those changes have been made the plugin should be switched to no longer depend on `logstash-core`, but rather the `logstash-core-plugin-api '> 2.1.17'`

**Comment by robinhultman** [comment]
Any progress on this?

**Comment by brahmnes** [comment]
I am not sure anyone is looking at this at the moment. You are welcomed to submit a PR.

**Comment by robinhultman** [comment]
Ok, I found no code that had to be rewritten so I just switched the dependency as @andrewvc suggested and that worked. 
https://github.com/Azure/azure-diagnostics-tools/pull/55

**Comment by AlessandroMenti** [comment]
The patch works, but apparently no update was published on rubygems.org. @brahmnes, could you please take care of that as well?

**Comment by brahmnes** [comment]
New version of logstash-input-azureeventhub 0.9.7 is now on rubygems.org.
