### ISSUE TITLE
Update logstash-input-azurewadtable on RubyGems.org

### ISSUE THREAD

**Issue by Sterlingg** [Azure/azure-diagnostics-tools#49]
The last version of "logstash-input-azurewadtable" on RubyGems.org is in June, which doesn't include the latest commit that parses the PreciseTimeStamp field as a date.

The plugin: https://rubygems.org/gems/logstash-input-azurewadtable
The missing commit: https://github.com/Azure/azure-diagnostics-tools/commit/ad71e85ed5382d9027c52cce8ca35d2c1f635ecc

**Comment by brahmnes** [comment]
logstash-input-azurewadtable 0.9.11 is now available on rubygems.org, it has all the updated fixes so far.

**Comment by Sterlingg** [comment]
@brahmnes Thank you!
