### ISSUE TITLE
Continuation Token incorrectly reset

### ISSUE THREAD

**Issue by blane-directscale** [Azure/azure-diagnostics-tools#53]
Hello,  Looks like you don't support public pull requests, so I'll report this here.  

I found a issue with the logstash blob plugin.  If the number of items in the container exceeds the paging value (default is 5000) then the list_blob_names method will get stuck in an infant loop.

Code in /Logstash/logstash-input-azureblob/lib/logstash/inputs/azureblob.rb

```
    loop do
      continuation_token = NIL
      entries = @azure_blob.list_blobs(@container, { :timeout => 10, :marker => continuation_token})

```
The continuation_token is cleared each time thought the loop so it will always fetch the first page.  An easy way to dup this is to setup a container with 10 blobs and then set the max_results option of the list_blobs call to 2 or something smaller that the number in the container.

The code should initialize the value only once before entering the loop.  

```
    continuation_token = NIL
    loop do
      entries = @azure_blob.list_blobs(@container, { :timeout => 10, :marker => continuation_token})

```
-Thanks

**Comment by brahmnes** [comment]
Thanks for the catch!
We do accept PR, feel free to submit one.

**Comment by brahmnes** [comment]
This should be in 0.9.7 now.
