### ISSUE TITLE
Problem with grab logs in plugin logstash-input-azureblob

### ISSUE THREAD

**Issue by NeSViT** [Azure/azure-diagnostics-tools#57]
Hello to all, 

Maybe someone could help me with my problem that I've started to observe during working with "logstash-input-azureblob" plugin.

What're environment in my case:
1. Azure WebApp that puts its logs to Azure Container.
2. ELK on dedicated server (Logstash 2.2.4, ElasticSearch 2.4.3, Kibana 4.4.2)
3. Logstash has installed plugin "logstash-input-azureblob".
4. Logstash has created by me pattern "webapp" that handle IIS logs from WebApp.
5. Logstash has configuration file that wrote in order to [manual](https://github.com/Azure/azure-diagnostics-tools/blob/master/Logstash/logstash-input-azureblob/README.md) 

WebApp has log line:
```
2016-12-29 11:19:48 TEST-WEBAPP GET / X-ARR-LOG-ID=7445e01d-8664-4e1a-87af-64c179e5ee1a 80 - 211.222.222.222 AlwaysOn ARRAffinity=5c3efa83fd2d9d2509fafa36caed15a78ecc79cf1ebf4e44d1e7410f694d7ce6 - test-webapp.azurewebsites.net 200 0 0 1209 692 78
```
My logstash pattern for handling logs above:
```
LOGTIMESTAMP %{YEAR}-%{MONTHNUM}-%{MONTHDAY} %{HOUR}:?%{MINUTE}(?::?%{SECOND})

WEBAPP %{LOGTIMESTAMP:logtimestamp} %{NOTSPACE:ServiceName} %{WORD:Method} %{URIPATHPARAM:UriStem} %{NOTSPACE:UriQuery} %{NUMBER:ServerPort} %{NOTSPACE} %{IPV4:ClientIP} %{NOTSPACE:UserAgent} %{NOTSPACE:Trash} %{NOTSPACE:Referrer} %{HOSTNAME:Host} %{NUMBER:ProtocolStatus} %{NUMBER:SubStatus} %{NUMBER:Win32Status} %{NUMBER:BytesSent} %{NUMBER:BytesReceived} %{NUMBER:RequestTime}
```

My logstash configuration file:
**INPUT SECTION:**
```
input
{
        azureblob
        {
                storage_account_name => "azurestorage"
                storage_access_key => "=="
                container => "log-webserver"
                
                # change default codec from json_lines ot line
                codec => line
                # mark input with type azureblob
                type => azureblob
        }
}
```
**FILTER SECTION**
```
filter
{
    # check if azureblob
    if [type] == "azureblob" {

        # drop system IIS messages 
        if ([message] =~ "^#") {
            drop {}
        }

        # apply custom pattern WEBAPP to field message 
        grok {
            match => { "message" => "%{WEBAPP}" }
        }

        # match date logtimestamp to @timestamp
        date {
            match => [ "logtimestamp", "YYYY-MM-dd HH:mm:ss" ]
            timezone => "Etc/UTC"
            target => "@timestamp"
            locale => "en"
        }

         # remove field logtimestamp 
         mutate {
            remove_field => [ "logtimestamp"]
         }
    }
}
```

**OUTPUT SECTION**
```
output
{
        stdout {}
        elasticsearch {
                hosts => "localhost"
                index => "logstash-azureblob-%{+YYYY-MM-dd}"
        }
}

```

And finally I'll try to describe a problem that I see in Kibana.

When plugin goes to blob container to get data from azure blob container it creates *.lock file in each folder. After that something goes wrong because it takes only 2 messages from log file.

Grabbed logs have @timestamp:
```
2016-12-31 05:59:25
2016-12-31 05:59:25
```
and two previous
 ```
2016-12-31 04:59:25
2016-12-31 04:59:25
```
and so on. 

Also if I manually delete *.lock file from container then plugin gets all data from log and shows it in Kibana correctly.
Looks like file file *.lock creates very early or something like this. 

Do you have any suggestion regarding this issue? Or I did mistake somewhere?

**Comment by NeSViT** [comment]
Hello @EmFl 

I've implemented @Nordes [fork](https://github.com/Nordes/azure-diagnostics-tools/tree/master/Logstash/logstash-input-azureblob) to the my environment ( #8 ).  

@Nordes I wish to send you a big thanks! It's really cool decision.

All logs that placed in a blob container is collected with this plugin.  I'm testing it during 3 days and it still looks good. 

For other folk I posted here my **INPUT SECTION** from my logstash:

```
input
{
    azureblob
    {
        storage_account_name => "teststorage"
        storage_access_key => "blablabla=="
        container => "testblobcontainer"
        codec                => "line"         
        sincedb              => "sincedb"
        type => azureblob
        sleep_time           =>  60
    }
}
```

**Comment by mrahmatellah** [comment]
Hello,

I added the same content of your input file but i have an error : 

 azureblob plugin is using the 'milestone' method to declare the version of the plugin this method is deprecated in favor of declaring the version inside the gemspec. {:level=>:warn}
Unknown setting 'sincedb' for azureblob {:level=>:error}
Error: Something is wrong with your configuration. {:level=>:error}

Can you help plz,

Also your grok not working for me i had change it to :

%{TIMESTAMP_ISO8601:log_timestamp} %{NOTSPACE:ServiceName} %{WORD:Method} %{URIPATHPARAM:UriStem} %{NOTSPACE:UriQuery} %{NUMBER:ServerPort} %{NOTSPACE} %{IPV4:ClientIP} %{NOTSPACE:UserAgent} %{NOTSPACE:Cookies} %{NOTSPACE:Referrer} %{HOSTNAME:Host} %{NUMBER:ProtocolStatus} %{NUMBER:SubStatus} %{NUMBER:Win32Status} %{NUMBER:BytesSent} %{NUMBER:BytesReceived} %{NUMBER:RequestTime}
