### ISSUE TITLE
ES-MultiNode -> CreateElasticSearchCluster enable CORS?

### ISSUE THREAD

**Issue by bondarewicz** [Azure/azure-diagnostics-tools#59]
Hi there,
We've used the CreateElasticSearchCluster PowerShell script to create a ES cluster based on those [docs](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-diagnostic-how-to-use-elasticsearch). We are able to successfully ssh into admin node however we are unable to locate the `elasticsearch.yml` file...

based on below section taken from [here](https://raw.githubusercontent.com/Azure/azure-diagnostics-tools/master/ES-MultiNode/es-ubuntu-install.sh) it seem like the path to config file should be `/etc/elasticsearch/elasticsearch.yml` ?

```
echo "#################### Configuring ES service ####################"
echo "cluster.name: $cluster_name" >> /etc/elasticsearch/elasticsearch.yml
echo "node.name: ${HOSTNAME}" >> /etc/elasticsearch/elasticsearch.yml
```

Did anyone experienced something similar ?

**Comment by karolz-ms** [comment]
Yes, this is the expected location of the elasticsearch.yml file, but it applies to ES cluster nodes only. The -admin node is just a jumpbox, it does not have any ES services running.

Hope this helps!

**Comment by karolz-ms** [comment]
To clarify: you can SSH from the -admin node to the ES nodes and make any updates to ES configuration locally.

**Comment by bondarewicz** [comment]
@karolz-ms thanks for the info! I thought it might be the case, are you aware of any resources on how can I ssh to cluster nodes via admin node? I've tried ssh to admin and then from there ssh to node but I got a permission denied, do I have to create a ssh tunnel ? Any help appreciated.

**Comment by karolz-ms** [comment]
The same key file that is used for the admin node can be used to ssh to cluster nodes. So usually I just scp the key file to the admin node and then ssh from admin nodes to cluster nodes.
