### ISSUE TITLE
collection_start_time_utc offset

### ISSUE THREAD

**Issue by clintonm9** [Azure/azure-diagnostics-tools#6]
Currently, if the logstash server restarts or goes down we would miss the logs while it wasn't running.

Is there a way to make an offset to make it at least go back 24 hours or something like that?

If I misunderstand how it works let me know.

Thanks!

**Comment by brahmnes** [comment]
The main reason was we don't want to process the same data twice. The config parameter let's you specify a specific time, if preferred. An alternative may be to have logstash writes a timestamp to a file on teardown, but that wouldn't help the case where logstash crashes.

**Comment by clintonm9** [comment]
It seems there could be a way for it to know it is already added or not.

**Comment by brahmnes** [comment]
What's your suggestion?

**Comment by clintonm9** [comment]
I don't have one off the top of my head. 

How does file beat do it?

**Comment by brahmnes** [comment]
It looks like file beat writes it to a file. We can consider doing the same thing.

**Comment by jstangroome** [comment]
For reference the S3 input plugin records the watermark timestamp in a file like this:

https://github.com/logstash-plugins/logstash-input-s3/blob/master/lib/logstash/inputs/s3.rb#L343-L370

**Comment by EmFl** [comment]
is anyone working on something like this ? Might need to implement it soon. For now if we're missing too many data we're simply reparsing the full days event to a new index and then delete the previous one. Works well enough but not fantastic...

**Comment by brahmnes** [comment]
Are you want a offset parameter that you can specify in the config? Or you need the plugin to remember the timestamp of the last transferred event?

**Comment by EmFl** [comment]
I need the plugin to remember the timestamp of the last transferred event and in case of crash to start as it does now from the current timestamp

**Comment by brahmnes** [comment]
I see. It's a good addition, feel free to submit a PR.

**Comment by xiaomi7732** [comment]
@clintonm9,
Starting from 0.9.8, the plugin will remember the offset of last access. Thus, you can resume from the point where logstash exits. (Find the gem here: https://rubygems.org/gems/logstash-input-azureblob)

For advanced scenarios, please refer the readme:
https://github.com/Azure/azure-diagnostics-tools/blob/master/Logstash/logstash-input-azureblob/README.md.
