### ISSUE TITLE
Bundler could not find compatible versions for gem "logstash-core"

### ISSUE THREAD

**Issue by zp-j** [Azure/azure-diagnostics-tools#62]
Hi,

As mentioned in issue [#46](https://github.com/Azure/azure-diagnostics-tools/issues/46), there are still four plugins that need to update their configurations:

- Azure Blob
- Azure Topic
- Azure Topic Threadable
- ApplicationInsights

For example, for Azure blob I got this error below:

```shell
# ./logstash-plugin install logstash-input-azureblob
Validating logstash-input-azureblob
Installing logstash-input-azureblob
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 5.2.0)

  In Gemfile:
    logstash-core-plugin-api (>= 0) java depends on
      logstash-core (= 5.2.0) java

    logstash-input-azureblob (>= 0) java depends on
      logstash-core (< 2.0.0, >= 1.4.0) java

    logstash-core (>= 0) java
```

**Comment by zp-j** [comment]
Hi @nizarq ,

Can you please help to bump a new version to [rubygems.org](https://rubygems.org/gems/logstash-input-azureblob).

Thanks!
Zhipeng

**Comment by brahmnes** [comment]
Uploaded to rubygems.org
