### ISSUE TITLE
AppServices's Diagnostics logs - azure blob

### ISSUE THREAD

**Issue by Wesam18** [Azure/azure-diagnostics-tools#64]
I am trying to move Azure AppServices's Diagnostics logs to Logstash trough Azure blob. The problem that, the Logstash Blob plugin read the file one time and lock the file and never check that file again while Azure AppService continues updating the same file.

**Comment by EmFl** [comment]
Hello, 
Please check the fork by Nordes he added a sincedb in azure table and it works well.

**Comment by Wesam18** [comment]
To my knowledge, Azure AppServices are capable of sending logs to FTP location or Blob storage only. Correct me if I am wrong. 

I have submitted a PR that added another mode ( Backup mode) to the blob storage which backup the file and delete the original file instead of the lock mechanism (Check the PR #65 )

**Comment by brahmnes** [comment]
Hi Wesam18,

I looked at your PR and I don't understand how the backup mode helps with the problem. The reason is, even if you move the blob to a name with .bak suffix, the same blob doesn't get picked up on the next iteration.

**Comment by Wesam18** [comment]
Hello Brahmnes, 

Let me clarify that. I am not creating the blob name with "lock" as a suffix so the same file name could be picked up again in the next iteration if the AppService generates any new logs.

**Comment by brahmnes** [comment]
Hi Wesam18,

Sorry for the delay, I thought through your solution. It looks creative and simple. Two main problems are: 1. Copying blobs are expensive, but at the same time, I don't have a better suggestion.
2. The copy + delete without a lock doesn't work well for multi-reader cases.

If you can think of a way to address #2, that would be good.

**Comment by Wesam18** [comment]
Hi @brahmnes  , 
I have addressed your second comment. Kindly check and let me if you have any further comments.

**Comment by xiaomi7732** [comment]
@Wesam18,
Starting from logstash-input-azureblobs 0.9.8, flexibility is provided that you can decide how to continuous consuming the logs.

Please refer the readme, making use of the new parameters of `interval` and `registry_create_policy`:
https://github.com/Azure/azure-diagnostics-tools/blob/master/Logstash/logstash-input-azureblob/README.md
