### ISSUE TITLE
logstash-input-azureeventhub fails to find new messages

### ISSUE THREAD

**Issue by ewanlyall** [Azure/azure-diagnostics-tools#66]
When logstash is started, the azureeventhub plugin successfully reads in all messages from where it left off... But it fails to find new messages on subsequent polling cycles.

The debug logs show the following every 30s (as per my config), but otherwise there are no errors.
```
[2017-02-17T16:11:48,036][DEBUG][logstash.inputs.azureeventhub]   03 --- No message
[2017-02-17T16:11:48,036][DEBUG][logstash.inputs.azureeventhub]   01 --- No message
[2017-02-17T16:11:48,036][DEBUG][logstash.inputs.azureeventhub]   02 --- No message
[2017-02-17T16:11:48,036][DEBUG][logstash.inputs.azureeventhub]   00 --- No message
```
But I know that there are unread messages in the eventhub and again, restarting logstash will read them in.

**my environment**
logstash version:
```
# logstash --version
logstash 5.2.0
```

plugin version:
```
# logstash-plugin list --verbose | grep azureeventhub
logstash-input-azureeventhub (0.9.7)
```

logstash input:
```
  azureeventhub {
    username => "logstash-policy"
    namespace => "my_namespace"
    eventhub => "insights-logs-auditevent"
    partitions => 4
    codec => "json"
    type => "keyvault-audit-logs"
    key => "my_key"
    thread_wait_sec => 30
  }
```

**Comment by yoanisgil** [comment]
Running in to the same issue here:

Logstash version:
```
# logstash --version
logstash 2.3.4
```

Plugin version:

```
logstash-plugin list --verbose | grep azure
Ignoring ffi-1.9.13 because its extensions are not built.  Try: gem pristine ffi --version 1.9.13
logstash-input-azurewadeventhub (0.9.7)
```

Plugin config:

```ruby
input {
  azurewadeventhub {
    key => 'key'
    username => 'username'
    eventhub => 'eventhub'
    namespace => 'namespace'
    partitions => 2
    time_since_epoch_millis => 1490328000000
  }
}
output {
   elasticsearch {
     hosts => ['IP'] index => 'wad'
   }
   stdout { codec => rubydebug }
}
```

@ewanlyall how did you manage to get the debug output from the plugin?

**Comment by ewanlyall** [comment]
@yoanisgil the method of enabling debug logging changed between logstash 2.x and 5.x. I see you are on 2.3.4 (I was using 5.2.0).

Under 2.x you need to start logstash with the `--debug` flag. As per https://www.elastic.co/guide/en/logstash/2.3/command-line-flags.html

Under 5.x you have more options... see https://www.elastic.co/guide/en/logstash/5.0/command-line-flags.html and https://www.elastic.co/guide/en/logstash/5.0/logging.html
With the command line flag
```
--log.level DEBUG
```

or using the log4j2.properties file, set something like
```
rootLogger.level = debug
```
alternatively, with the API you can enable debug for a specific logstash module. The other benefit of this is that you don't have to restart logstash to enable it.
To list the modules
```
curl localhost:9600/_node/logging?pretty
```
then to enable for the azureeventhub plugin
```
curl -XPUT localhost:9600/_node/logging -d '{"logger.logstash.inputs.azureeventhub" : "DEBUG"}'
```

**Comment by clguimanMSFT** [comment]
@ewanlyall 
Please verify with the latest master build. You need to checkout the code, then from the plugin folder build and install:
```
gem build logstash-input-azureeventhub.gemspec
sudo /usr/share/logstash/bin/logstash-plugin install ./logstash-input-azureeventhub-0.9.8-java.gem
```

**Comment by ewanlyall** [comment]
@clguimanMSFT 
I'm no longer working in that role and don't have access to an azure environment to test with. @smarshal-Quest, if this is still of interest to you, please test and report back

**Comment by clguimanMSFT** [comment]
The issue should be fixed with v. 0.9.8.
