### ISSUE TITLE
logstash-input-azureblob doesn't support proxy

### ISSUE THREAD

**Issue by hassanbabaie** [Azure/azure-diagnostics-tools#69]
Is there a way to set the plug to support a Proxy Server?

**Comment by brahmnes** [comment]
Can you clarify? Do you mean your environment is behind a proxy server?

**Comment by hassanbabaie** [comment]
Hi @brahmnes yes exactly. This is in regards to NSG Flow Logs and based of the following link: https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-visualize-nsg-flow-logs-open-source-tools

I've tested setting this up our Corporate Network (Outbound Web Proxy based access) and Off our corporate network (direct/default route).

Now getting it all setup using a proxy was a pain but right now I don;t think Logstash is pulling the files down from the Azure storage blob and I think that is because the logstash-plugin "logstash-input-azureblob" doesn't have a proxy setting?

If it doesn't need one do you know what Linux ENV setting it might take a proxy setting from?

Hope this makes sense

thanks

Hass

**Comment by brahmnes** [comment]
You can take a look at the azure-storage-ruby library: https://github.com/azure/azure-storage-ruby
A quick peak at http_client.rb seems to indicate HTTP_PROXY or HTTPS_PROXY may help. However, I haven't tried or verified.

**Comment by hassanbabaie** [comment]
Thanks @brahmnes so in theory if I have these set I should be good; I'll test internally over the next few days

thank you for your quick feedback

**Comment by hassanbabaie** [comment]
Hi @brahmnes I've checked and it's for sure and issue getting out over the internet the logstash error is:

[2017-03-10T18:45:53,056][ERROR][logstash.inputs.azureblob] Oh My, An error occurred. {:exception=>#<Faraday::TimeoutError>}

Any thoughts on how I can use the proxy settings you mentioned?

Hass

**Comment by brahmnes** [comment]
HTTP_PROXY is environment variable. Have you looked at [https://github.com/Azure/azure-storage-ruby/blob/master/lib/azure/storage/core/http_client.rb]?

**Comment by hassanbabaie** [comment]
Hi @brahmnes maybe I'm miss-understanding. To confirm:

As far as I can tell I'm only using: azureblob.rb after following the install process on the Microsoft site for NSG flow logs. 

I have HTTP_PROXY and HTTPS_PROXY Environment variables set on the server but I still get the timeout error. 

I can see that the link you sent me to http_client.rb has a section to take the ENV variables for a proxy however I don't see that same section in azureblob.rb.

Do I need to manually add it in?

again thank you for your time on this

Hass

**Comment by brahmnes** [comment]
azureblob.rb depends on the azure ruby sdk, see the require statement at line 5.
Double check to make sure the environment variable is defined for the logstash process.

**Comment by brahmnes** [comment]
Hi @hassanbabaie 
Did this solve your problem?

**Comment by outlawza** [comment]
Hi 

Can i put in for a feature request to get this issue resolved. Setting environment variables for the outbound proxy does not get passed to the service account that runs the logstash application. If one has a look at the logstash-input-s3 plugin, we are able to add a string variable to the config (proxy_uri) forcing external access to the destination via the specified server. 

This plugin lacks that option. 

Running logstash as the root user results in a successful connection to the azureblob container and we are able to ingest the logs. Running the service as root is not recommended in our environment. It would be great to be able to define the outbound proxy. 

Thanks 

Terry

**Comment by brahmnes** [comment]
Hi outlawza,

I am not sure I understand the difficulty. I think you just need to find the command, or service init script, and make sure logstash is launched with the environment variable.

Making the plugin take a parameter and setting it inside is possible, but I like to understand why the workaround didn't work.

thanks,
Brahmnes

**Comment by hassanbabaie** [comment]
Quick update, no I was unable to solve it but that might have been lack of skill on my part, I'll go back through in the next few days and will let you know

**Comment by xiaomi7732** [comment]
I'll close this for now. @hassanbabaie , please let us know if there is progress.
