### ISSUE TITLE
The shutdown process appears to be stalled due to busy or blocked plugin

### ISSUE THREAD

**Issue by clintonm9** [Azure/azure-diagnostics-tools#7]
{:timestamp=>"2016-04-26T13:56:42.352000-0500", :message=>"The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.", :level=>:error}

**Comment by EmFl** [comment]
Hello,
From what I've seen most of the code has while true loops so they don't interrupt when you try to shutdown logstash. I made a fork of this to get it running with newer version of logstash and fixed some of the loop issues as well if you want to give it a try.

**Comment by brahmnes** [comment]
Thank you for the comment. I assume you are referring to adding logic in the teardown method so the while loop can exit? Or you have other suggestions on how to fix the loop issues?

**Comment by EmFl** [comment]
I don't know for older version of logstash but for >2 there are now methods available : 
https://www.elastic.co/guide/en/logstash/current/contributing-to-logstash.html#_plugin_api_changes_phrase_revisionflag_added_revision_2_0_added_in_2_0_phrase
Also the input example has been modified to show this :
https://github.com/logstash-plugins/logstash-input-example/blob/master/lib/logstash/inputs/example.rb

```
def run(queue)
    # we can abort the loop if stop? becomes true
    while !stop?
      event = LogStash::Event.new("message" => @message, "host" => @host)
      decorate(event)
      queue << event
      # because the sleep interval can be big, when shutdown happens
      # we want to be able to abort the sleep
      # Stud.stoppable_sleep will frequently evaluate the given block
      # and abort the sleep(@interval) if the return value is true
      Stud.stoppable_sleep(@interval) { stop? }
    end # loop
  end # def run
```

**Comment by brahmnes** [comment]
Thank you for the suggestion. Seems like a good change to make, we will consider that. If you have the change, feel free to submit a PR

**Comment by whiskeyjay** [comment]
I have updated the code for the WAD Table plugin and the WAD Event Hubs plugin to take advantage of the stop? method.
