### ISSUE TITLE
java.lang.NegativeArraySizeException on blob plugin

### ISSUE THREAD

**Issue by paulpc** [Azure/azure-diagnostics-tools#70]
20:34:05.581 [[main]<azureblob] ERROR logstash.inputs.azureblob - Oh My, An error occurred. {:exception=>java.lang.NegativeArraySizeException}

I have some JSON files in blob ranging in size between 1 and 1.7 GB. After some troubleshooting of JVM size and VM size, I now get this error.

**Comment by brahmnes** [comment]
Do you believe it's due to the size of the blob?
Looking at https://github.com/Azure/azure-storage-ruby/blob/master/lib/azure/storage/blob/blob.rb, it looks like it may be possible to add an option to get the blob piece by piece. Perhaps you can modify the plugin to see if that helps?

**Comment by xiaomi7732** [comment]
@paulpc,
This looks like a bug lying in azure-storage sdk in terms of bring down big blob. Is it possible to share us a copy of your blob?

**Comment by paulpc** [comment]
Let me see if I can do it on a sanitized copy of the data

**Comment by xiaomi7732** [comment]
@paulpc, thank you in advance!

**Comment by xiaomi7732** [comment]
@paulpc,
How is things going up there?

**Comment by xiaomi7732** [comment]
I can repro this issue now by having a huge log file (> 1.5G). It failed to load the whole file by calling into storage sdk to get the blob.
@clguimanMSFT, if time permits, could you please take a look will paging loading the blob solving the issue?

**Comment by clguimanMSFT** [comment]
The issue should be fixed in v.0.9.12
@paulpc can you please check with the latest version?

**Comment by brahmnes** [comment]
Closing since the issue is now fixed
