### ISSUE TITLE
logstash-input-azuretopic connection error

### ISSUE THREAD

**Issue by ballm** [Azure/azure-diagnostics-tools#72]
On completing the 4 parameters namespace, access_key, subscription, topic I get a connection failed message.

I have accessed the topic using the same subscription and access key from the same box using the http rest protocol, so I am sure the box logstash is running on can access the queue and that the values are valid.

a real life example of the parameters may help, for example is namespace just the namespace or the full uri? I've viewed the code, and it seems correct with the Microsoft documentation for gem access. So at a loss as to what I should be using for the parameters. The error message doesn't give much away, other than stating "Oh My, An error occurred" followed by connection error (flooding the log file with 100's of lines in a few seconds)

**Comment by dimachait** [comment]
I just experienced the same issue, it looks like this plugin requires the service bus setup using ACS Authentication and when you create a service bus via the new Azure portal it doesn't create an ACS namespace (<sb_namespace>-sb.accesscontrol.windows.net)

I think this should be enhanced to support SAS as that's the recommended authentication now by Microsoft's documentation
There is a closed issue on the azure-sdk for ruby that shows how to implement this with SAS Authentication: https://github.com/Azure/azure-sdk-for-ruby/issues/426

**Comment by gjoris** [comment]
I'm having the exact same issue. Has anyone fixed this yet?

**Comment by addp009** [comment]
I'm having the same issue, but I was able to modify it to work with SAS key. I'll make a PR.

**Comment by addp009** [comment]
PR created: https://github.com/Azure/azure-diagnostics-tools/pull/81

**Comment by xiaomi7732** [comment]
@ballm, @dimachait, @gjoris,
Appreciate @addp009's contribution, SAS key access is supported. Check out PR #81.

**Comment by addp009** [comment]
Thanks @xiaomi7732 for reviewing and merging quickly!  Any idea how to publish the SAS key support to the public repos? My logstash instances are still pulling the old version. Is it just a bumping the version number in logstash-input-azuretopic.gemspec?

**Comment by xiaomi7732** [comment]
@addp009:
Done. Checkout 0.9.8 of the gem: https://rubygems.org/gems/logstash-input-azuretopic
