### ISSUE TITLE
logstash blob storage plugin data pull frequency

### ISSUE THREAD

**Issue by mliu1212** [Azure/azure-diagnostics-tools#73]
Whats the data pull frequency for the blob storage logstash input? If a file is being written to over an hour does the plugin still forward the file, or wait until its finished writing?

**Comment by xiaomi7732** [comment]
Hi @mliu1212,
The issue you encountered is a known bug and should have been addressed in 0.9.8. Please refer:
https://rubygems.org/gems/logstash-input-azureblob
