### ISSUE TITLE
Authorization Failure while trying this plugin

### ISSUE THREAD

**Issue by SyCode7** [Azure/azure-diagnostics-tools#76]
Hi, thanks a lot for proviing thsi plugin. I have continously had authentication failures while tring this plugin pout since yesterday. Please is there any thing I an doing wrong.... my logstash config is as follows 
`
azureeventhub
    {
      key => "myEventhub Primary AccessKey"
      username => "eventhub key name"
      namespace => "eventhub namespace"
      eventhub => "eventhub"
      partitions => 4

    }

`

**Comment by brahmnes** [comment]
Per the documentation, these are the values you should provide:

key: The shared access key to the target event hub.
username: The name of the shared access policy.
namespace: Event Hub namespace.
eventhub: Event Hub name.

For the key, you should provide the key specific for the access policy, not the root manage access key. You should see the key when you click on details for the access policy in the Azure portal.

**Comment by clguimanMSFT** [comment]
@SyCode7 did brahmnes' comment help? Are you still having this issue?

**Comment by clguimanMSFT** [comment]
Closing the issue because the reporter didn't reply in a while
