### ISSUE TITLE
Logstash cannot parse log4j messages from azureblob 

### ISSUE THREAD

**Issue by johey** [Azure/azure-diagnostics-tools#77]
I have a java app hosted as a webapp with Tomcat 8 on Azure. The app is logging with log4j 1.2 to ApplicationInsights, which is continously storing it on a blob storage account. Then I have an ELK stack running on Azure, collecting logs from the blob storage using logstash-input-azureblob. Here something goes wrong though. Elasticsearch seems not to like the format of the data sent from logstash. In the logstash logs I can see loads of messages, for instance:

`[2017-06-15T18:45:16,915][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-2017.06.15", :_type=>"%{[@metadata][type]}", :_routing=>nil}, 2017-06-15T18:45:16.781Z %{host} {severityLevel=Verbose, sourceType=Log4j, level=DEBUG, raw=http-outgoing-11129 >> "[0xb7][[0xe9][0xe3][0x8a]k,_[0xb][0xd1]:6[\n]", loggerName=com.microsoft.applicationinsights.core.dependencies.http.wire, threadName=Thread-18, timestamp=2017-06-15T17:21:03+00:00}], :response=>{"index"=>{"_index"=>"logstash-2017.06.15", "_type"=>"%{[@metadata][type]}", "_id"=>"AVytEuooYuUhVejAIgiT", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [message]", "caused_by"=>{"type"=>"illegal_state_exception", "reason"=>"Can't get text on a START_OBJECT at 1:926"}}}}}`

Why is this happening and what can I do to fix it?

ubuntu 16.04.02
logstash 5.4.1
elasticsearch 5.4.1

**Comment by brahmnes** [comment]
The azureblob plugin just takes each line that ends with a linefeed and send it to elasticsearch, so it works best with plain text logs.
You can download the blob and see what format application insights is producing.

**Comment by xiaomi7732** [comment]
This is not specific to the input plugin. This issue looks like the output of the logstash is not accepted by ElasticSearch. Here is an example of how to use proper codecs and filter to provide data for elastic search:
[mporting IIS logs into Elasticsearch with Logstash](https://blog.sstorie.com/importing-iis-logs-into-elasticsearch-with-logstash/)

Some official documents for your reference as well.
https://www.elastic.co/guide/en/logstash/current/codec-plugins.html
https://www.elastic.co/guide/en/logstash/current/filter-plugins.html 

I'll close this issue for now. If you still need help to get it work, please feel free to reactive it with your log content as samples.
