### ISSUE TITLE
need help understanding azureblob input

### ISSUE THREAD

**Issue by EmFl** [Azure/azure-diagnostics-tools#8]
Hello,
I'm trying to understand how the azureblob input works, right now I see it pushing data on the initial run but then nothing happens except if I remove the lock file (which pushes the whole file again).
Looking at the code, I think it goes to fetch the content only when it can create the .lock file. And ignores everything if a .lock file already exists. 
Is my understanding correct ? If so, how should I proceed to fetch the changes in my blob ?
Thanks

**Comment by brahmnes** [comment]
Your understanding is correct. It currently makes the assumption that if a blob shows up in the container, it's final. If a new blob comes in, it will pick it up. The lock file is really just a way to track it has seen the file and not process it again.

We are considering removing this plugin because it hasn't been too useful. If you have suggestions on making it more useful, or you have an interesting use case, feel free to comment.

**Comment by EmFl** [comment]
I have a use case where an application sends logs to the blob so it gets updated and needs to be parsed continuously.
I was thinking something along the lines of storing the ETAG, creation date, byte size and then on subsequent run comparing creation date, if it matches comparing ETAG, if it doesn't match then we request the blob with start range being the bytessize retrieved during the previous run.
If creation date doesn't match, drop the saved ETAG/ByteSize and parse from the beginning.

There would probably be some case where you could parse a partial data but I would be willing to accept that.

**Comment by clintonm9** [comment]
To make sure I understand correctly, if you are pulling from tables like WADServiceFabricAPIEventTable and new logs are added to the table, will it push those changes to logstash? I am guessing there might be a difference from how the blobs and tables work.

**Comment by EmFl** [comment]
The table data is refreshed yes it follows a different workflow

**Comment by Nordes** [comment]
Actually it would be nice if it could use a sincedb scheme. Keep the last bit read and start again from there (I did the code in C#, in an experimental app in order to do it). Actually, it is mainly because the IIS logs are pushed in the hours folder and updated each X seconds. So to keep track I created a local sincedb and I avoid also to scan already scanned files, or at least, since it's IIS logs, I know that old files won't get updated.

**Comment by Nordes** [comment]
@EmFl  : In the end I did an implementation, I need to do more testing, but it works quite well. Once it's more tested I will try to do a pull request.

See my [fork](https://github.com/Nordes/azure-diagnostics-tools/tree/master/Logstash/logstash-input-azureblob).

New parameters introduced: 
* sleep_time (sleep time between a rescan of the container)
* sincedb (use Azure Table to keep track)
* ignore_older (like file input)
* start_position (like file input)
* path_prefix (array of folder to watch in the container)

**Comment by EmFl** [comment]
@Nordes looks nice, we've changed our azure diagnostic processing to push our log file to azure table storage so I'm not in need of that anymore and I won't be able to test sorry. However couple of ideas to make it even better :
Add a field for each blob in the azure storage table with an identifier for the logstash process (to lock the blob to a current logstash indexer). Then, have that column emptied on logstash shutdown.
Once another logstash indexer comes into the picture, lists the blobs, checks the table, if column is empty, it adds itself to it, then start indexing from last byte stored in table.
This could allow multiple logstash to index the same files (not at the same time of course) and provide some kind of high availability mechanism.
You'll probably require a new setting for something like : lastindexedtimeout which would be checked by the logstash indexer and would allow you to start processing "locked" blob that haven't been processed in the last xx mimnutes (in case of logstash agent crash and so without removing the name of the agent on the table).

**Comment by trondhindenes** [comment]
@Nordes you're implementation is infinetely better than the MS one. I'd really like to see your changes merged in. Just a question, will the sincedb setting allow for multiple logstash servers indexing the same blob container without getting in the way of each other? I have no ruby experience so not able to be of any help here I'm afraid. In any case, great job!

**Comment by EmFl** [comment]
@Nordes I could not find a pull request with your changes is this something you're planning on merging by any chance ?

**Comment by Nordes** [comment]
Hello,

Sorry for not answering. I actually did not do any pull request. My code was not fully tested and I prefered to leave it aside. But if you want, you can take it and ensure that there are no CPU intensive or anything wrong with my branch.

I plan to relook at it in a near future, but for now I am quite busy :).

**Comment by EmFl** [comment]
Thanks for the reply, I'll start using it very soon on our platform, guess we'll see what happens  :)
I'm closing this issue for now. Will open specific ones if needed.
