### ISSUE TITLE
The implementation in 0.9.9 is not handling json that contains '{' or '}' as values for json codec

### ISSUE THREAD

**Issue by xiaomi7732** [Azure/azure-diagnostics-tools#85]
When parsing json, the current algorithm is not handling escaping text of '{' or '}' as values. This need to be fixed.

**Comment by xiaomi7732** [comment]
Guys, please vote if you encountered this issue. Your feedback is very important helping us decide the priorities.

**Comment by xiaomi7732** [comment]
Some raw thinking here:
* The most sense is to introduce existing json parser to handle all cases.
* The caveat is that we are loading partial (not well formatted) json. We can solve this by either make it well formatted json or find a parse that works with partial / streaming json.

**Comment by clguimanMSFT** [comment]
Fixed in v.0.9.12 which has a proper Json parser
